/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.controlador;
import com.toedter.calendar.JDateChooser;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author nico-alarcon
 */
public class PaginaRegistroPago extends javax.swing.JDialog {

    /**
     * Creates new form RegistroPago
     */
    public PaginaRegistroPago(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public JLabel getjLMontoPaciente() {
        return jLMontoPaciente;
    }

    public JLabel getjLNombrePaciente() {
        return jLNombrePaciente;
    }

    public JLabel getLbVuelto() {
        return lbVuelto;
    }

    public JTextField getTxtDniPaciente() {
        return txtDniPaciente;
    }

    public JTextField getTxtMontoNuevo() {
        return txtMontoNuevo;
    }

    public JTextField getTxtNumeroRecibo() {
        return txtNumeroRecibo;
    }

    public JDateChooser getDateChoosser() {
        return dateChoosser;
    }

    public JTable getTablaPagos() {
        return tablaPagos;
    }

    public JLabel getjLSaldo() {
        return jLSaldo;
    }

    public JLabel getjLTotalAbonado() {
        return jLTotalAbonado;
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDniPaciente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPagos = new javax.swing.JTable();
        btnCancelar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnBorrarPago = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMontoNuevo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLNombrePaciente = new javax.swing.JLabel();
        jLMontoPaciente = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNumeroRecibo = new javax.swing.JTextField();
        lbVuelto = new javax.swing.JLabel();
        dateChoosser = new com.toedter.calendar.JDateChooser();
        jLSaldo = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLTotalAbonado = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnNuevoPago = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setText("Total Abonado:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, -1, -1));

        jLabel3.setForeground(new java.awt.Color(0, 153, 255));
        jLabel3.setText("Monto por mes:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, -1, -1));

        txtDniPaciente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDniPacienteFocusLost(evt);
            }
        });
        txtDniPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDniPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(txtDniPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 150, -1));

        tablaPagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N° de Recibo", "Fecha del Pago", "Monto Abonado"
            }
        ));
        jScrollPane1.setViewportView(tablaPagos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 750, 130));

        btnCancelar.setForeground(new java.awt.Color(0, 153, 255));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/volver.png"))); // NOI18N
        btnCancelar.setText("Volver");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 440, 120, -1));

        btnRegistrar.setForeground(new java.awt.Color(0, 153, 255));
        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/registrar.png"))); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 440, -1, -1));

        btnBorrarPago.setForeground(new java.awt.Color(0, 153, 255));
        btnBorrarPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/Salir.png"))); // NOI18N
        btnBorrarPago.setText("Borrar Pago");
        btnBorrarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarPagoActionPerformed(evt);
            }
        });
        getContentPane().add(btnBorrarPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, 30));

        jLabel4.setForeground(new java.awt.Color(0, 153, 255));
        jLabel4.setText("DNI:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel5.setForeground(new java.awt.Color(0, 153, 255));
        jLabel5.setText("Mes a pagar: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        jLabel6.setForeground(new java.awt.Color(0, 153, 255));
        jLabel6.setText("N° de Recibo:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, -1, -1));
        getContentPane().add(txtMontoNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 80, 20));

        jLabel8.setForeground(new java.awt.Color(0, 153, 255));
        jLabel8.setText("Paciente:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, -1));

        jLNombrePaciente.setText(" ");
        getContentPane().add(jLNombrePaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 250, -1));

        jLMontoPaciente.setText(" ");
        getContentPane().add(jLMontoPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 100, 60, -1));

        jLabel7.setForeground(new java.awt.Color(0, 153, 255));
        jLabel7.setText("Monto:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, -1, -1));
        getContentPane().add(txtNumeroRecibo, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 380, 130, -1));
        getContentPane().add(lbVuelto, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, 70, 20));
        getContentPane().add(dateChoosser, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 130, -1));

        jLSaldo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        getContentPane().add(jLSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 290, 110, 20));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 153, 255));
        jLabel10.setText("Saldo:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, -1, -1));

        jLTotalAbonado.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        getContentPane().add(jLTotalAbonado, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 110, 20));

        jLabel12.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 153, 255));
        jLabel12.setText("Registro de Pago");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        jLabel13.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 153, 255));
        jLabel13.setText("Nuevo Pago:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        btnNuevoPago.setForeground(new java.awt.Color(0, 153, 255));
        btnNuevoPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/registrar_pago.png"))); // NOI18N
        btnNuevoPago.setText("Nuevo Pago");
        btnNuevoPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoPagoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/fondo_secundario.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        controlador.registrarPago(this);
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        controlador.volverAPrincipal(this);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtDniPacienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDniPacienteFocusLost
        controlador.buscarPaciente(this);
    }//GEN-LAST:event_txtDniPacienteFocusLost

    private void txtDniPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDniPacienteActionPerformed

    private void btnBorrarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarPagoActionPerformed
        controlador.eliminarPago(this);
    }//GEN-LAST:event_btnBorrarPagoActionPerformed

    private void btnNuevoPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoPagoActionPerformed
        controlador.iniciarNuevoPago(this);
    }//GEN-LAST:event_btnNuevoPagoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaRegistroPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaRegistroPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaRegistroPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaRegistroPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PaginaRegistroPago dialog = new PaginaRegistroPago(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrarPago;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnNuevoPago;
    private javax.swing.JButton btnRegistrar;
    private com.toedter.calendar.JDateChooser dateChoosser;
    private javax.swing.JLabel jLMontoPaciente;
    private javax.swing.JLabel jLNombrePaciente;
    private javax.swing.JLabel jLSaldo;
    private javax.swing.JLabel jLTotalAbonado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbVuelto;
    private javax.swing.JTable tablaPagos;
    private javax.swing.JTextField txtDniPaciente;
    private javax.swing.JTextField txtMontoNuevo;
    private javax.swing.JTextField txtNumeroRecibo;
    // End of variables declaration//GEN-END:variables
}
